package org.ryi.sbjph.model;

// Generated 5 oct. 2017 21:41:51 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysUsers generated by hbm2java
 */
@Entity
@Table(name = "sys_users")
@NamedQuery(name = "SysUsers.findAllUsers", 
query = "from SysUsers as u inner join fetch u.sysUserRoleses")


public class SysUsers  {

	private String username;
	private String password;
	private boolean enabled;
	private Set<SysUserRoles> sysUserRoleses = new HashSet<SysUserRoles>(0);

	public SysUsers() {
	}

	public SysUsers(String username, String password, boolean enabled) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
	}

	public SysUsers(String username, String password, boolean enabled,
			Set<SysUserRoles> sysUserRoleses) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.sysUserRoleses = sysUserRoleses;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "enabled", nullable = false)
	public boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUsers")
	public Set<SysUserRoles> getSysUserRoleses() {
		return this.sysUserRoleses;
	}

	public void setSysUserRoleses(Set<SysUserRoles> sysUserRoleses) {
		this.sysUserRoleses = sysUserRoleses;
	}

}
